#!/bin/bash

source /etc/update-motd.d/colors.txt

DOCKER="/usr/bin/docker"

show_docker_info() {
    if [[ ! -x "${DOCKER}" ]]; then return; fi

    local raw_data
    raw_data=$("${DOCKER}" ps -a --format '{{.Names}}|{{.Status}}' 2>/dev/null | sort -k1)

    if [[ -z "${raw_data}" ]]; then
        echo -e " ${TITLE_COLOR}Docker Containers...: ${NC}${TEXT_COLOR}0 / 0 ${NC}"
        return
    fi

    local totalcount=0
    local runningcount=0
    local container_list=""

    while IFS='|' read -r name status; do
        ((totalcount++))
        
        local color
        case "${status}" in
            Up*)
                ((runningcount++))
                color="${TEXT_COLOR}"
                ;;
            Exited\ \(0\)*) # Чистый выход (код 0)
                color="${DEFAULT_COLOR}"
                ;;
            Exited*) # Выход с ошибкой (любой другой код)
                color="${ERR_COLOR}"
                ;;
            Created*|Paused*|Restarting*)
                color="${DEFAULT_COLOR}"
                ;;
            Dead*|Removing*)
                color="${ERR_COLOR}"
                ;;
            *)
                color="${NC}"
                ;;
        esac
        
        container_list+="$(printf "    %-27s${color}%s${NC}\n" "${name}" "${status}")\n"
    done <<< "${raw_data}"

    echo -e " ${TITLE_COLOR}Docker Containers...: ${NC}${TEXT_COLOR}${runningcount} / ${totalcount}${NC}"
    echo -e -n "${container_list}"
}

show_docker_info
